<?php

/**
 * @file
 * Contains social_kpi_lite.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function social_kpi_lite_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the social_kpi_lite module.
    case 'help.page.social_kpi_lite':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Implements KPI Analytics for Open Social distribution.') . '</p>';
      return $output;

    default:
  }
}
